info:
  component: Gateway Server

zuul:
  routes:
    musica:
      path: /musica/**
      serviceId: musica-service
    playlist:
      path: /playlist/**
      serviceId: playlist-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8765
