spring:
  profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.handson.micdomingues.playlist.configs.SQLiteDialect
  datasource:
    url: jdbc:sqlite:MyMusic.db
    driverClassName: org.sqlite.JDBC
server:
  port: 8081

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/